- docker_path: github.com/dockerfile/nginx
  options:
    detach: true
    name: nginx-server
    ports:
      80: 8080
  port: 80
  public_url: http://localhost:8080
- docker_path: https://github.com/mendhak/docker-http-https-echo
  options:
    detach: true
    name: test-echo-server
  port: 8080
  public_url: http://localhost:10000
